# ETSY Micro-Agent Refactor - Commander Edition

import os
import time
import random
from datetime import datetime
from content_generator import generate_description, generate_image
from rent_pricer import suggest_price
from rent_logger import log_rent_activity
from ai_personas import CEO, Optimizer  # Placeholder for agent layer

# Trend-based content strategy (draft extraction from core_knowledge)
trendy_keywords = [
    "AI-generated planner PDF", "Printable Budget Tracker", "Aesthetic digital calendar",
    "Customizable wedding invite template", "Minimalist resume pack"
]

def select_trendy_title():
    return random.choice(trendy_keywords)

def run_commander_cycle(n=3):
    for i in range(n):
        trend = select_trendy_title()
        title = f"{trend} - AutoGenerated #{i+1}"
        print(f"\n🎯 Commander Bot generating: {title}")

        prompt = f"Write an emotional, modern Etsy listing for: {trend}"
        description = generate_description(prompt)
        image_url = generate_image(trend)
        price = suggest_price(description, beat_competitor=True)

        log_rent_activity({
            "title": title,
            "description": description,
            "image_url": image_url,
            "price": price,
            "trend": trend,
            "timestamp": datetime.now().isoformat(),
            "meta": {
                "bot": "etsy_commander",
                "strategy": "trend+ai+pricecut",
                "checkpoints": ["description", "image", "pricing", "log"],
                "lessons": []
            }
        })

        print(f"📌 {title} listed at ${price:.2f}")
        time.sleep(2)

if __name__ == "__main__":
    run_commander_cycle(n=3)
